version: 0.2

phases:
  install:
    commands:
      - apk update
      - apk add ruby-dev gcc make curl build-base libc-dev libffi-dev zlib-dev libxml2-dev libgcrypt-dev libxslt-dev python python-dev py-pip
      - pip install awscli
      - bundle config build.nokogiri --use-system-libraries
      - rm -rf /srv/jekyll/*
      - git clone ${source_repository} /srv/jekyll
      - cd /srv/jekyll
      - bundle install
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - cd /srv/jekyll
      - jekyll build -d /tmp/_site/
      - echo "******** Uploading to S3 ********"
      - aws s3 sync --acl public-read /tmp/_site/ s3://${bucket_name}
