version: 0.2

phases:
  install:
    commands:
      - echo "***** Pushing website source to S3 *****"
  build:
    commands:
      - wget -q -O ./list/effective_tld_names.dat https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat
      - cp -f ./list/effective_tld_names.dat ./list/public_suffix_list.dat
      - aws s3 sync --acl public-read ./ s3://${bucket_name}

